In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression

In [3]:
dx = pd.read_csv('Logistic_X_Train.csv')
dy = pd.read_csv('Logistic_Y_Train.csv')
dt = pd.read_csv('Logistic_X_Test.csv')

In [11]:
#normalize = preprocessing.MinMaxScaler()
standardize = preprocessing.StandardScaler()
#X_train = normalize.fit_transform(dx)
X_train = standardize.fit_transform(dx)
print(X_train)
#X_test = normalize.fit_transform(dt)
X_test = standardize.fit_transform(dt)
print(X_test)

[[-0.93471307 -0.24439694 -0.46140414]
 [-0.7823013  -0.19327286 -1.08586573]
 [-0.46707053  0.56681072 -1.17534766]
 ...
 [ 0.06059095  0.62470809 -1.83827342]
 [ 1.13777964 -0.13681202  1.22033571]
 [-0.74013008 -0.42526137 -1.29728616]]
[[-0.57728341 -1.25801397 -2.13531524]
 [-0.9409651   0.42552683 -0.35535257]
 [ 1.4881487   0.90057735  1.13155462]
 ...
 [-0.89902113 -0.06811659 -0.67149703]
 [-0.39689119  0.8153689  -0.84694422]
 [ 0.42578784 -0.42861965  0.32194475]]


In [8]:
Y_train=dy.values

In [12]:
classifier =  LogisticRegression().fit(X_train, Y_train)
outcomes = classifier.predict(X_test)
outcomes

c:\users\ankit kumar\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\ankit kumar\appdata\local\programs\python\python36-32\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1,

In [13]:
df1 = pd.DataFrame({'lable' : outcomes})
df1.to_csv('output.csv',index = False)